# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_detail',
            name='profile_image',
            field=models.ImageField(default='/image_uploads/default_image.png', upload_to='image_uploads/'),
        ),
    ]
