# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20180911_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_detail',
            name='profile_image',
            field=models.ImageField(default='/home/rails/demo_projects/user_profile_details/user_details/image_uploads/default_image.png', upload_to='image_uploads/'),
        ),
    ]
