# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20180911_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_detail',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='image_uploads/'),
        ),
    ]
